
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlgfrndzvfkjkyowmwkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsZ2ZybmR6dmZramt5b3dtd2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MDk4NzAsImV4cCI6MjA1ODI4NTg3MH0.3-DdavQsiAZdwPULJ1qLnTJKF6Tht18srVLmVWCpiC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'supabase.auth.token',
    }
  }
);
